Mooc\QuizBundle\Entity\Badge:
    type: entity
    table: badge
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
